on: [push, pull_request]
defaults:
  run:
    shell: bash
jobs:
  build-sdist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: python -m venv .venv
      - run: .venv/bin/pip install build
      - run: .venv/bin/python -m build --sdist
      - uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: dist/transmission_delete_unwanted-*.tar.gz
          if-no-files-found: error
  build-wheel:
    runs-on: ubuntu-latest
    needs: build-sdist
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: sdist
      - run:
          tar --gzip --extract --verbose --strip-components=1 --file
          transmission_delete_unwanted-*.tar.gz
      - run: python -m venv .venv
      - run: .venv/bin/pip install build
      - run: .venv/bin/python -m build --wheel
      - uses: actions/upload-artifact@v4
        with:
          name: wheel
          path: dist/transmission_delete_unwanted-*.whl
          if-no-files-found: error
  pytest:
    runs-on: ubuntu-latest
    needs: build-wheel
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: wheel
      - run: python -m venv .venv
      - run: .venv/bin/pip install transmission_delete_unwanted-*.whl
      - run: .venv/bin/pip install --requirement pytest-requirements.txt
      - run: sudo apt-get install --yes transmission-daemon
      - run: .venv/bin/pytest
  pylint:
    runs-on: ubuntu-latest
    needs: build-sdist
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: sdist
      - run: tar --gzip --extract --verbose --strip-components=1 --file transmission_delete_unwanted-*.tar.gz
      - run: python -m venv .venv
      - run: .venv/bin/pip install
             --requirement pylint-requirements.txt
             --requirement requirements.txt
             --requirement pytest-requirements.txt
      - run: .venv/bin/pylint --verbose src transmission_delete_unwanted_tests
        env:
          PYTHONPATH: .