on: [push, pull_request]
defaults:
  run:
    shell: bash
jobs:
  build-sdist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: python -m venv .venv
      - run: .venv/bin/pip install build
      - run: .venv/bin/python -m build --sdist
      - uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: dist/transmission_delete_unwanted-*.tar.gz
          if-no-files-found: error