on: [push, pull_request]
defaults:
  run:
    shell: bash
jobs:
  build-sdist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: python -m venv .venv
      - run: .venv/bin/pip install build
      - run: .venv/bin/python -m build --sdist
      - uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: dist/transmission_delete_unwanted-*.tar.gz
          if-no-files-found: error
  build-wheel:
    runs-on: ubuntu-latest
    needs: build-sdist
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: sdist
      - run:
          tar --gzip --extract --verbose --strip-components=1 --file
          transmission_delete_unwanted-*.tar.gz
      - run: python -m venv .venv
      - run: .venv/bin/pip install build
      - run: .venv/bin/python -m build --wheel
      - uses: actions/upload-artifact@v4
        with:
          name: wheel
          path: dist/transmission_delete_unwanted-*.whl
          if-no-files-found: error
